### ISSUE TITLE
Add EFO TA features to the term precision classification model

### ISSUE THREAD

**Issue by eric-czech** [related-sciences/nxontology-ml#33]
refs: https://github.com/related-sciences/nxontology-ml/issues/2

It would likely benefit models like those in https://github.com/related-sciences/nxontology-ml/pull/28 if they included the presence of EFO TA terms as features.  Specifically, a single binary indicator for all TA terms associated with a single EFO term would be great (i.e. following the semantics of [MultiLabelBinarizer](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MultiLabelBinarizer.html)).

**Comment by yonromai** [comment]
Closed by #34, feel free to re-open if needed.
