### ISSUE TITLE
Allow to configure cache location

### ISSUE THREAD

**Issue by yonromai** [related-sciences/nxontology-ml#46]
Let's allow the user to pass a location to `train_predict`. As far as the best default that makes sense when running nxontology-ml from its source repo and when as an imported library... not sure.

Slightly related is the comment at https://github.com/related-sciences/nxontology-ml/pull/41#issuecomment-1755685996. I think we should move `data/efo_otar_slim_v3.43.0_rs_classification.tsv` into the package directory.

_Originally posted by @dhimmel in https://github.com/related-sciences/nxontology-ml/issues/35#issuecomment-1760407576_

**Comment by dhimmel** [comment]
Can we also change this logging statement to info from debug:

https://github.com/related-sciences/nxontology-ml/blob/3c6cc0ffef3cac8d91d3226af23ef157a0ca286a/nxontology_ml/text_embeddings/embeddings_model.py#L121-L122

nxontology-data defaults to showing INFO not DEBUG and it'd always be good to see which cache file is used.

**Comment by yonromai** [comment]
> Can we also change this logging statement to info from debug:

Sure np

>  I think it should only get logged once right?

Yes it should
